---
version: 2.1

references:
  images:
    jdk: &JDK_IMAGE circleci/openjdk:8-jdk
    ubuntu: &UBUNTU_IMAGE ubuntu-2004:202104-01

  environment: &ENVIRONMENT
    MID_SERVER_VERSION: quebec.05-26-2021_0941

jobs:
  test:
    docker:
      - image: *JDK_IMAGE
    environment:
      <<: *ENVIRONMENT

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run:
          name: Run unit tests
          command: ./gradlew test

      # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      - store_test_results:
          path: build/test-results/test
      # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports/tests/test

  integrationTest:
    machine:
      image: *UBUNTU_IMAGE
    environment:
      <<: *ENVIRONMENT
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run:
          name: Run integration tests
          command: ./gradlew integrationTest

      - store_test_results:
          path: build/test-results/integrationTest
      - store_artifacts:
          path: build/test-results/integrationTest
      - store_artifacts:
          path: build/reports/tests/integrationTest

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
      - integrationTest:
          requires:
            - test
