name: Tests

# Run this workflow on pushes and manually
on: [push, workflow_dispatch]

env:
  MID_SERVER_VERSION: sandiego.02-07-2022_1650

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Docker
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
      - name: Test
        run: ./gradlew test
      - name: Integration test
        run: ./gradlew integrationTest
      